USE [master]
GO

/****** Object:  Database [DefaultConnection]    Script Date: 9/23/2015 10:34:33 AM ******/
CREATE DATABASE [DefaultConnection]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DefaultConnection', FILENAME = N'C:\Users\Christopher\DefaultConnection.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DefaultConnection_log', FILENAME = N'C:\Users\Christopher\DefaultConnection_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DefaultConnection] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DefaultConnection].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DefaultConnection] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DefaultConnection] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DefaultConnection] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DefaultConnection] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DefaultConnection] SET ARITHABORT OFF 
GO

ALTER DATABASE [DefaultConnection] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DefaultConnection] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DefaultConnection] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DefaultConnection] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DefaultConnection] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DefaultConnection] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DefaultConnection] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DefaultConnection] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DefaultConnection] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DefaultConnection] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DefaultConnection] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DefaultConnection] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DefaultConnection] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DefaultConnection] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DefaultConnection] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DefaultConnection] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DefaultConnection] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DefaultConnection] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DefaultConnection] SET  MULTI_USER 
GO

ALTER DATABASE [DefaultConnection] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DefaultConnection] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DefaultConnection] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DefaultConnection] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DefaultConnection] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DefaultConnection] SET  READ_WRITE 
GO

